version: "3.8"

services:
  web:
    build: .
    container_name: hik_app
    ports:
      - "8004:8004"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8004
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token eyJhIjoiYTZiNjllYzU4N2QzNTdiYWFiYmM4YTY3ZWM5Njk0OGQiLCJ0IjoiMTA4NTVkNWYtZjJhNC00ZDMxLWFjYzQtNzI1Y2M2NTVhYWNkIiwicyI6Ik4yWXhNVGN4T1dFdFpqWTFNUzAwWm1SbExUa3hPRFF0WmpJek9HRTJZV1JoWm1WaiJ9
    restart: unless-stopped
    depends_on:
      - web
